backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "img"
collections:
  - name: pages
    label: Pages
    files:
      - label: "Lessons Page"
        name: lessons
        file: "_data/lessons.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Blurb, name: blurb, widget: string}
          - {label: Image Path, name: img, widget: string}