name: Test Jekyll Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7.4, 3.0.2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # caches and runs bundle automatically - see
    # https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec jekyll build
